[project]
name = "capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kevinhav", email = "kevin.havis@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "pandas>=3.0.5",
]

[project.scripts]
capstone = "capstone:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
